spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 127.0.0.1
    port: 6379

  shardingsphere:
    datasource:
      enabled: true
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    props:
      # 日志显示 SQL
      sql.show: true
    sharding:
      tables:
        test_bigsql:
          actualDataNodes: ds0.test_bigsql$->{1..3}
          tableStrategy:
            standard:
              shardingColumn: id
              precise-algorithm-class-name: com.courage.shardingsphere.jdbc.service.sharding.PreciseShardingTableAlgorithm
  servlet:
    multipart:
      enabled: true
      max-file-size: 400MB
      max-request-size: 400MB